version: '3.7'
services:
  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - app-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPICS_REPLICATION_FACTOR: 1
    networks:
      - app-network
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
  user:
    build:
      context: taskmanager/user/.
    container_name: user
    restart: always
    environment:
      DATABASE_NAME: dev
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: mariadb
      AUTH_SERVICE_URL: auth:8001
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: user-events
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mariadb
      - kafka
  task:
    build:
      context: taskmanager/task/.
    container_name: task
    restart: always
    environment:
      DATABASE_NAME: dev
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: mariadb
      AUTH_SERVICE_URL: auth:8001
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: "task-events"
      GATEWAY_HOST: user:8000
    ports:
      - "8003:8003"
    networks:
      - app-network
    depends_on:
      - mariadb
      - kafka
  auth:
    build:
      context: taskmanager/auth/.
    container_name: auth
    restart: always
    environment:
      DATABASE_NAME: dev
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: mariadb
    ports:
      - "8001:8001"
    networks:
      - app-network
  notification:
    build:
      context: taskmanager/notification/.
    container_name: notification
    restart: always
    environment:
      KAFKA_TOPIC: "task-events"
      KAFKA_HOST: kafka
    ports:
      - "8004:8004"
    networks:
      - app-network
    depends_on:
      - kafka
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - task
      - user
      - auth
      - notification
    networks:
      - app-network
  celery:
    build:
      context: taskmanager/task/.
    container_name: celery
    command: ['celery', '-A', 'main.celery', 'worker', '-l', 'info']
    restart: always
    depends_on:
      - task
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
